package com.emall.dataobject;

import java.util.Date;

public class AdminDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.admin_id
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.admin_name
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.is_used
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private Boolean isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.password
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.phone
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.email
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.gender
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private Boolean gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.created_date
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_admin_info.updated_date
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    private Date updatedDate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.admin_id
     *
     * @return the value of em_admin_info.admin_id
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.admin_id
     *
     * @param adminId the value for em_admin_info.admin_id
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.admin_name
     *
     * @return the value of em_admin_info.admin_name
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.admin_name
     *
     * @param adminName the value for em_admin_info.admin_name
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.is_used
     *
     * @return the value of em_admin_info.is_used
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public Boolean getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.is_used
     *
     * @param isUsed the value for em_admin_info.is_used
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setIsUsed(Boolean isUsed) {
        this.isUsed = isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.password
     *
     * @return the value of em_admin_info.password
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.password
     *
     * @param password the value for em_admin_info.password
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.phone
     *
     * @return the value of em_admin_info.phone
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.phone
     *
     * @param phone the value for em_admin_info.phone
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.email
     *
     * @return the value of em_admin_info.email
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.email
     *
     * @param email the value for em_admin_info.email
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.gender
     *
     * @return the value of em_admin_info.gender
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.gender
     *
     * @param gender the value for em_admin_info.gender
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.created_date
     *
     * @return the value of em_admin_info.created_date
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.created_date
     *
     * @param createdDate the value for em_admin_info.created_date
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_admin_info.updated_date
     *
     * @return the value of em_admin_info.updated_date
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_admin_info.updated_date
     *
     * @param updatedDate the value for em_admin_info.updated_date
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}