package com.emall.dataobject;

public class IndexListDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list.list_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private Integer listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list.list_name
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String listName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list.img_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list.source_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list.sorted
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private Integer sorted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list.list_id
     *
     * @return the value of em_index_list.list_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list.list_id
     *
     * @param listId the value for em_index_list.list_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list.list_name
     *
     * @return the value of em_index_list.list_name
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getListName() {
        return listName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list.list_name
     *
     * @param listName the value for em_index_list.list_name
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setListName(String listName) {
        this.listName = listName == null ? null : listName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list.img_url
     *
     * @return the value of em_index_list.img_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list.img_url
     *
     * @param imgUrl the value for em_index_list.img_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list.source_url
     *
     * @return the value of em_index_list.source_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list.source_url
     *
     * @param sourceUrl the value for em_index_list.source_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list.sorted
     *
     * @return the value of em_index_list.sorted
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public Integer getSorted() {
        return sorted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list.sorted
     *
     * @param sorted the value for em_index_list.sorted
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setSorted(Integer sorted) {
        this.sorted = sorted;
    }
}