package com.emall.dataobject;

import java.math.BigDecimal;

public class IndexListItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.item_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.list_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private Integer listId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.source_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String sourceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.desc
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.old_price
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private BigDecimal oldPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.discount_type
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String discountType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.discount
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private String discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column em_index_list_item.sorted
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    private Integer sorted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.item_id
     *
     * @return the value of em_index_list_item.item_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.item_id
     *
     * @param itemId the value for em_index_list_item.item_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.list_id
     *
     * @return the value of em_index_list_item.list_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public Integer getListId() {
        return listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.list_id
     *
     * @param listId the value for em_index_list_item.list_id
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setListId(Integer listId) {
        this.listId = listId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.source_url
     *
     * @return the value of em_index_list_item.source_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getSourceUrl() {
        return sourceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.source_url
     *
     * @param sourceUrl the value for em_index_list_item.source_url
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl == null ? null : sourceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.desc
     *
     * @return the value of em_index_list_item.desc
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.desc
     *
     * @param desc the value for em_index_list_item.desc
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.old_price
     *
     * @return the value of em_index_list_item.old_price
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public BigDecimal getOldPrice() {
        return oldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.old_price
     *
     * @param oldPrice the value for em_index_list_item.old_price
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setOldPrice(BigDecimal oldPrice) {
        this.oldPrice = oldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.discount_type
     *
     * @return the value of em_index_list_item.discount_type
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getDiscountType() {
        return discountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.discount_type
     *
     * @param discountType the value for em_index_list_item.discount_type
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setDiscountType(String discountType) {
        this.discountType = discountType == null ? null : discountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.discount
     *
     * @return the value of em_index_list_item.discount
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public String getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.discount
     *
     * @param discount the value for em_index_list_item.discount
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setDiscount(String discount) {
        this.discount = discount == null ? null : discount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column em_index_list_item.sorted
     *
     * @return the value of em_index_list_item.sorted
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public Integer getSorted() {
        return sorted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column em_index_list_item.sorted
     *
     * @param sorted the value for em_index_list_item.sorted
     *
     * @mbg.generated Sat Mar 30 20:03:01 CST 2019
     */
    public void setSorted(Integer sorted) {
        this.sorted = sorted;
    }
}