package com.emall.dao;

import com.emall.dataobject.AdminDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface AdminDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_admin_info
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    int deleteByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_admin_info
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    int insert(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_admin_info
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    int insertSelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_admin_info
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    AdminDO selectByPrimaryKey(String adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_admin_info
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    int updateByPrimaryKeySelective(AdminDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_admin_info
     *
     * @mbg.generated Fri Mar 29 14:42:33 CST 2019
     */
    int updateByPrimaryKey(AdminDO record);

    List<AdminDO> getAllAdmin();

    String getPassword(@Param("adminName") String adminName);
}