package com.emall.dao;

import com.emall.dataobject.BuyerCommentDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface BuyerCommentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int deleteByPrimaryKey(String buyerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int insert(BuyerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int insertSelective(BuyerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    BuyerCommentDO selectByPrimaryKey(String buyerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int updateByPrimaryKeySelective(BuyerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(BuyerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_buyer_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int updateByPrimaryKey(BuyerCommentDO record);

    List<BuyerCommentDO> getAllComment();
}