package com.emall.dao;

import com.emall.dataobject.IndexListItemDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface IndexListItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_index_list_item
     *
     * @mbg.generated Sun Mar 31 16:34:16 CST 2019
     */
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_index_list_item
     *
     * @mbg.generated Sun Mar 31 16:34:16 CST 2019
     */
    int insert(IndexListItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_index_list_item
     *
     * @mbg.generated Sun Mar 31 16:34:16 CST 2019
     */
    int insertSelective(IndexListItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_index_list_item
     *
     * @mbg.generated Sun Mar 31 16:34:16 CST 2019
     */
    IndexListItemDO selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_index_list_item
     *
     * @mbg.generated Sun Mar 31 16:34:16 CST 2019
     */
    int updateByPrimaryKeySelective(IndexListItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_index_list_item
     *
     * @mbg.generated Sun Mar 31 16:34:16 CST 2019
     */
    int updateByPrimaryKey(IndexListItemDO record);

    List<IndexListItemDO> getListItemByListId(int listId);

    int deleteByItemId(String itemId);

}