package com.emall.dao;

import com.emall.dataobject.NavigationItemDO;
import org.springframework.stereotype.Component;

import java.util.List;


@Component
public interface NavigationItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_navigation_item
     *
     * @mbg.generated Sun Mar 31 22:16:43 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_navigation_item
     *
     * @mbg.generated Sun Mar 31 22:16:43 CST 2019
     */
    int insert(NavigationItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_navigation_item
     *
     * @mbg.generated Sun Mar 31 22:16:43 CST 2019
     */
    int insertSelective(NavigationItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_navigation_item
     *
     * @mbg.generated Sun Mar 31 22:16:43 CST 2019
     */
    NavigationItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_navigation_item
     *
     * @mbg.generated Sun Mar 31 22:16:43 CST 2019
     */
    int updateByPrimaryKeySelective(NavigationItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_navigation_item
     *
     * @mbg.generated Sun Mar 31 22:16:43 CST 2019
     */
    int updateByPrimaryKey(NavigationItemDO record);

    List<NavigationItemDO> getAllNavigationItem();

    int deleteByItemId(String itemId);
}