package com.emall.dao;

import com.emall.dataobject.SellerCommentDO;

public interface SellerCommentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int deleteByPrimaryKey(String sellerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int insert(SellerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int insertSelective(SellerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    SellerCommentDO selectByPrimaryKey(String sellerCommentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int updateByPrimaryKeySelective(SellerCommentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_seller_comment
     *
     * @mbg.generated Thu Feb 21 10:15:21 CST 2019
     */
    int updateByPrimaryKey(SellerCommentDO record);
}