package com.emall.dao;

import com.emall.dataobject.ShufflingFigureDataDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ShufflingFigureDataDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_shufflingFigureData
     *
     * @mbg.generated Sun Mar 31 19:48:33 CST 2019
     */
    int deleteByPrimaryKey(String shufflingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_shufflingFigureData
     *
     * @mbg.generated Sun Mar 31 19:48:33 CST 2019
     */
    int insert(ShufflingFigureDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_shufflingFigureData
     *
     * @mbg.generated Sun Mar 31 19:48:33 CST 2019
     */
    int insertSelective(ShufflingFigureDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_shufflingFigureData
     *
     * @mbg.generated Sun Mar 31 19:48:33 CST 2019
     */
    ShufflingFigureDataDO selectByPrimaryKey(String shufflingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_shufflingFigureData
     *
     * @mbg.generated Sun Mar 31 19:48:33 CST 2019
     */
    int updateByPrimaryKeySelective(ShufflingFigureDataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_shufflingFigureData
     *
     * @mbg.generated Sun Mar 31 19:48:33 CST 2019
     */
    int updateByPrimaryKey(ShufflingFigureDataDO record);

    List<ShufflingFigureDataDO> getAllShufflingFigure();
}