package com.emall.dao;

import com.emall.dataobject.UserDO;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_info
     *
     * @mbg.generated Sat Mar 16 09:21:47 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_info
     *
     * @mbg.generated Sat Mar 16 09:21:47 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_info
     *
     * @mbg.generated Sat Mar 16 09:21:47 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_info
     *
     * @mbg.generated Sat Mar 16 09:21:47 CST 2019
     */
    UserDO selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_info
     *
     * @mbg.generated Sat Mar 16 09:21:47 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table em_user_info
     *
     * @mbg.generated Sat Mar 16 09:21:47 CST 2019
     */
    int updateByPrimaryKey(UserDO record);

    List<UserDO> getAllUser(int status);
}